# Site settings
title: Blog para c치lculo III
description: "Este es un blog para ir a침adiendo las tareas de C치lculo III"
url: "https://fjsantim.github.io/blog"
author:
  name: "Pranjal Dhole"
  email: "dhole.pranjal@gmail.com"
  url: "https://fjsantim.github.io"

# Build settings
baseurl: /science-blog-template/
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
genero: "C치lculo diferencial" # Blog genre
version: "1.0.1"    # Blog site version

# Disqus comments
comments: true      # used to enable disqus comments on site
dsq_shortname: science-blog-template # disqus shortname

# Options: Define which header/footer to use
custom_header: false
custom_nav_footer: false
reverse: false

# Plugins
plugins:
  - jekyll-paginate
